apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: soraland/test01
        name: web
        ports:
        - containerPort: 80
        resources: 
          requests: 
            cpu: 200m


==>최소 200m(= 0.2 Core)의 CPU를 보장할 수 있는 Worker Node에 해당 Pod를 스케줄링
